I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 134, in script
    if tutorial_done and level1_done:
  File "game/script.rpy", line 134, in <module>
    if tutorial_done and level1_done:
NameError: name 'level1_done' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 134, in script
    if tutorial_done and level1_done:
  File "/home/heinohen/jemma/renpy/renpy-8.2.3-sdk/renpy/ast.py", line 1845, in execute
    if renpy.python.py_eval(condition):
  File "/home/heinohen/jemma/renpy/renpy-8.2.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/heinohen/jemma/renpy/renpy-8.2.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 134, in <module>
    if tutorial_done and level1_done:
NameError: name 'level1_done' is not defined

Linux-6.8.0-40-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.3.24061702
Hero Farmer 1.0
Thu Aug 22 14:40:03 2024
